// MARK: - Generated Dummy for UserRepository
// Generated by SwiftMockGenerator
// This is a dummy implementation that does nothing

class UserRepositoryDummy: UserRepository {

    private override var users: [String: User] = []
    override var allUsers: [User] = []

    override init() {
        super.init()
    }

    override func createUser(name name: String, email email: String) -> User {
        // Dummy implementation - does nothing
        return User()
    }

    override func findUser(by id: String) -> User? {
        // Dummy implementation - does nothing
        return nil
    }

    override func updateUser(_ user: User) {
        // Dummy implementation - does nothing
    }

    override func deleteUser(id id: String) {
        // Dummy implementation - does nothing
    }

}