// MARK: - Generated Stub for CacheProtocol
// Generated by SwiftMockGenerator

class CacheProtocolStub: CacheProtocol {

    var size: Int { 0 }

    init() {}

    func store(_ value: T, for key: String) {}

    func retrieve(_ type: T.Type, for key: String) -> T? {
        return nil
    }

    func remove(for key: String) {}

    func clear() {}

}