// MARK: - Generated Spy for DataRepositoryProtocol
// Generated by SwiftMockGenerator

class DataRepositoryProtocolSpy: DataRepositoryProtocol {

    // MARK: - Call Tracking

    private(set) var saveCallCount = 0
    private(set) var loadCallCount = 0
    private(set) var deleteCallCount = 0
    private(set) var countCallCount = 0

    private(set) var saveCallParameters: [(Item)] = []
    private(set) var loadCallParameters: [(String)] = []
    private(set) var deleteCallParameters: [(String)] = []
    // No parameters for count

    // MARK: - Return Values

    var loadReturnValue: Item? = nil
    var countReturnValue: Int = 0

    var items: [Item] { [] }

    init() {}

    // MARK: - Reset
    func resetSpy() {
        saveCallCount = 0
        saveCallParameters = []
        loadCallCount = 0
        loadCallParameters = []
        deleteCallCount = 0
        deleteCallParameters = []
        countCallCount = 0
        countCallParameters = []
    }

    // MARK: - Method Implementations

    func save(_ item: Item) throws {
        saveCallCount += 1
        saveCallParameters.append((item))
    }

    func load(id id: String) throws -> Item? {
        loadCallCount += 1
        loadCallParameters.append((id))
        return loadReturnValue
    }

    func delete(id id: String) throws {
        deleteCallCount += 1
        deleteCallParameters.append((id))
    }

    func count() -> Int {
        countCallCount += 1
        return countReturnValue
    }

}