// MARK: - Generated Spy for NetworkManager
// Generated by SwiftMockGenerator

class NetworkManagerSpy: NetworkManager {

    // MARK: - Call Tracking

    private(set) var performRequestCallCount = 0
    private(set) var handleErrorCallCount = 0

    private(set) var performRequestCallParameters: [(String)] = []
    private(set) var handleErrorCallParameters: [(Error)] = []

    // MARK: - Return Values

    var performRequestReturnValue: String = ""

    override init() {
        super.init()
    }

    // MARK: - Reset
    func resetSpy() {
        performRequestCallCount = 0
        performRequestCallParameters = []
        handleErrorCallCount = 0
        handleErrorCallParameters = []
    }

    // MARK: - Method Overrides

    override func performRequest(endpoint endpoint: String) -> String {
        performRequestCallCount += 1
        performRequestCallParameters.append((endpoint))
        return performRequestReturnValue
    }

    override func handleError(_ error: Error) {
        handleErrorCallCount += 1
        handleErrorCallParameters.append((error))
    }

}