// MARK: - Generated Stub for authenticateUser
// Generated by SwiftMockGenerator

func authenticateUserStub(username username: String, password password: String) async throws -> String {
    return ""
}