// MARK: - Generated Dummy for APIConfiguration
// Generated by SwiftMockGenerator
// This is a dummy implementation that does nothing

struct APIConfigurationDummy: APIConfiguration {

    var baseURL: String = ""
    var apiKey: String = ""
    var timeout: TimeInterval = TimeInterval()

    init() {}

    func isValid() -> Bool {
        // Dummy implementation - does nothing
        return false
    }

    mutating func updateTimeout(_ newTimeout: TimeInterval) {
        // Dummy implementation - does nothing
    }

}