name: Main Branch Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Xcode ${{ matrix.xcode }}
    runs-on: ${{ matrix.os }}
    
    strategy:
        matrix:
          include:
            # Latest stable versions
            - os: macos-14
              xcode: '15.4'
              swift: '5.10'
        
        fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        
      - name: Show Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version
          
      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
            
      - name: Resolve dependencies
        run: swift package resolve
        
      - name: Build project
        run: swift build --configuration release
        
      - name: Run tests
        run: swift test --configuration release --parallel --enable-code-coverage
        
      - name: Verify coverage files
        run: |
          echo "Checking for coverage files..."
          find .build -name "*.json" -type f | grep -i codecov || echo "No codecov files found"
          echo "All codecov directories:"
          find .build -name "codecov" -type d
          echo "Coverage files found:"
          find .build -name "*.json" -path "*/codecov/*" -exec ls -la {} \;
          
      - name: Convert coverage to LCOV format
        run: |
          # Find the profdata file
          PROFDATA_FILE=$(find .build -name "*.profdata" | head -1)
          if [ -z "$PROFDATA_FILE" ]; then
            echo "No profdata file found"
            exit 1
          fi
          
          echo "Found profdata file: $PROFDATA_FILE"
          
          # Find the test executable
          TEST_XCTEST_DIR=$(find .build -name "*Tests.xctest" -type d | head -1)
          if [ -z "$TEST_XCTEST_DIR" ]; then
            echo "No test xctest directory found"
            exit 1
          fi
          
          # Look for the main executable (exclude dSYM directories and other files)
          TEST_EXECUTABLE=$(find "$TEST_XCTEST_DIR/Contents/MacOS" -type f -maxdepth 1 ! -name "*.dSYM" ! -name "*.yml" ! -name "*.plist" | head -1)
          if [ -z "$TEST_EXECUTABLE" ] || [ ! -f "$TEST_EXECUTABLE" ]; then
            echo "No test executable found in $TEST_XCTEST_DIR/Contents/MacOS"
            echo "Available files:"
            ls -la "$TEST_XCTEST_DIR/Contents/MacOS/"
            exit 1
          fi
          
          echo "Found test executable: $TEST_EXECUTABLE"
          
          # Convert to LCOV format
          xcrun llvm-cov export -format="lcov" "$TEST_EXECUTABLE" -instr-profile "$PROFDATA_FILE" > coverage.lcov
          
          echo "Generated coverage.lcov file:"
          ls -la coverage.lcov
          echo "First few lines of coverage file:"
          head -10 coverage.lcov
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.lcov
          fail_ci_if_error: false
          verbose: true